stages:
  - preparation

image: edbizarro/gitlab-ci-pipeline-php:7.3

# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: root
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: packages_marshmallow_dev_testing
  DB_HOST: mysql
  
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  
composer:
  stage: preparation
  script:
    - php -v
    - composer create-project --prefer-dist laravel/laravel laravel
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/